config/routes.rb
Rails.application.routes.draw do
  get 'plans/index'
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
resources :plans
root 'plans#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plan.rb
class Plan < ApplicationRecord
    validates :title, presence: true, length: { maximum: 20 }
    validates :start_date, presence: true
    validates :end_date, presence: true
    validates :memo, length: { maximum: 500 }, allow_blank: true
    validate :end_date_after_start_date
  
    private
  
    def end_date_after_start_date
      return if end_date.blank? || start_date.blank?
  
      if end_date <= start_date
        errors.add(:end_date, :end_date_after_start_date)
      end
    end
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = Plan.all
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    if @plan.save
      flash[:notice_create] = "スケジュールを登録しました"
      redirect_to :plans
    else
      flash[:notice_no_create] = "スケジュールの登録に失敗しました"
      render "new"
    end
  end

  def show
    @plan = Plan.find(params[:id])
  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def update
    @plan = Plan.find(params[:id])
    if @plan.update(plan_params)
      flash[:notice_update] = "スケジュールを更新しました"
      redirect_to :plans
    else
      flash[:notice_no_update] = "スケジュールを更新できませんでした"
      render "edit"
    end
  end

  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy
    flash[:notice_destroy] = "スケジュールを削除しました"
    redirect_to :plans
  end

  private
  def plan_params  # プライベートメソッド 
    params.require(:plan).permit(:title, :start_date, :end_date, :is_all_day, :memo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/layouts/application.html.erb
<!-- application.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title>Schedule</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <!-- フラッシュメッセージを表示する領域 -->
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>

  <%= yield %>
</body>
</html>

app/views/plans/edit.html.erb
<%= render "shared/partial" %>

<h3>予定の編集</h3>

<%= form_with model: @plan do |f| %>
  <table>
    <tr>
      <th><%= f.label :title ,"タイトル" %></th>
      <td><%= f.text_field :title %></td>
    </tr>

    <tr>
      <th><%= f.label :start_date ,"開始日" %></th>
      <td><%= f.date_field :start_date %></td>
    </tr>

    <tr>
      <th><%= f.label :end_date ,"終了日" %></th>
      <td><%= f.date_field :end_date %></td>
    </tr>

    <tr>
      <th><%= f.label :is_all_day ,"終日の場合はチェックを入れます" %></th>
      <td><%= f.check_box :is_all_day %></td>
    </tr>

    <tr>
      <th><%= f.label :memo ,"スケジュールメモ" %></th>
      <td><%= f.text_area :memo %></td>
    </tr>
  </table>

  <div>
    <ul>
      <li><%= f.submit "編集を完了する"%></li>
      <li><%= link_to "キャンセル", plans_path %></li>
    </ul>
  </div>

 <% if flash[:notice_no_update] %>
   <p class="notice"><%= flash[:notice_no_update] %></p>
 <% end %>

 <%= render "shared/error", obj: @plan %> 
 <% end %>

app/views/plans/index.html.erb
<h3>予定一覧</h3>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>更新日時</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.id %></td>
        <td><%= plan.title %></td>
        <td><%= plan.start_date %></td>
        <td><%= plan.end_date %></td>
        <td>
         <% if plan.is_all_day %>
         ⚪︎
         <% end %>
        </td>
        <td><%= plan.updated_at.strftime("%Y-%m-%d %H:%M") %></td>
        <td><%= link_to '詳細', plan_path(plan) %></td>
        <td><%= link_to '編集', edit_plan_path(plan) %></td>
        <td><%= link_to '削除', plan_path(plan), method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to "予定の新規登録", :new_plan %></p>

<p>現在の予定数: <%= @plans.count %></p>
<p>現在の日時: <%= Time.now.strftime("%Y-%m-%d %H:%M:%S") %></p>

app/views/plans/new.html.erb
<h3>ユーザー新規作成</h3>

<%= form_with model: @plan do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>
      <ul>
        <% @plan.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <th><%= f.label :title ,"タイトル" %></th>
      <td><%= f.text_field :title %></td>
    </tr>

    <tr>
      <th><%= f.label :start_date ,"開始日" %></th>
      <td><%= f.datetime_field :start_date %></td>
    </tr>

    <tr>
      <th><%= f.label :end_date ,"終了日" %></th>
      <td><%= f.datetime_field :end_date %></td>
    </tr>

    <tr>
      <th><%= f.label :is_all_day ,"終日の場合はチェックを入れます" %></th>
      <td><%= f.check_box :is_all_day %></td>
    </tr>

    <tr>
      <th><%= f.label :memo ,"スケジュールメモ" %></th>
      <td><%= f.text_area :memo %></td>
    </tr>
  </table>

  <div>
    <ul>
      <li><%= f.submit "登録完了する"%></li>
      <li><%= link_to "予定一覧に戻る", :plans %></li>
    </ul>
  </div>
<% end %>

app/views/plans/show.html.erb
<%= render "shared/partial" %>

<%= form_with model: @plan do |f| %>
  <table>
    <tr>
      <th>タイトル</th>
      <td><%= @plan.title %></td>
    </tr>

    <tr>
      <th>開始日</th>
      <td><%= l @plan.start_date %></td>
    </tr>

    <tr>
      <th>終了日</th>
      <td><%= l @plan.end_date %></td>
    </tr>

    <tr>
      <th>終日</th>
      <td><%= @plan.is_all_day ? '◯': '' %></td>
    </tr>

    <tr>
      <th>スケジュールメモ</th>
      <td><%= @plan.memo %></td>
    </tr>
  </table>

<% end %>

<%= link_to "一覧に戻る", :plans %>
<%= link_to "予定を編集する", edit_plan_path(@plan) %>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(obj.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_partial.html.erb
<div class="partial">
  <h4>スケジュール管理アプリ</h4>
</div>